// AceCue — build step (runs on Vercel via `node build.js`).
//
// We're a static site + edge functions. The only "build" we need is injecting
// the PUBLIC Supabase config (URL + anon key) into a small JS file the browser
// can read, so optional cloud-account sync works when the operator sets those
// env vars — and is silently disabled (guest-only) when they don't. No secret
// keys are ever written here; SUPABASE_ANON_KEY is designed to be public.

import { writeFileSync, mkdirSync, existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { deflateRawSync, crc32 } from "node:zlib";

const out = "public/js/env.js";
const cfg = {
  SUPABASE_URL: process.env.SUPABASE_URL || "",
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || "",
};

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by build.js — do not edit. Public config only.\n` +
    `window.ACECUE_ENV = ${JSON.stringify(cfg, null, 2)};\n`
);

console.log(
  `[build] wrote ${out} — Supabase ${cfg.SUPABASE_URL ? "configured (cloud sync ON)" : "not set (guest-only mode)"}`
);

// ---- package the extension into public/extension.zip for the download button ----
// Minimal zip writer (store + deflate) so the landing page can serve the plugin
// with no external tooling on the Vercel builder.
function walk(dir, base = dir, files = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, base, files);
    else files.push({ full, rel: full.slice(base.length + 1).replace(/\\/g, "/") });
  }
  return files;
}

function zip(files) {
  const chunks = [], central = [];
  let offset = 0;
  for (const { name, data } of files) {
    const nameBuf = Buffer.from(name);
    const comp = deflateRawSync(data);
    const crc = crc32(data) >>> 0;
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0, 6);
    local.writeUInt16LE(8, 8); // deflate
    local.writeUInt32LE(0, 10); // time/date
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(comp.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    chunks.push(local, nameBuf, comp);
    const cen = Buffer.alloc(46);
    cen.writeUInt32LE(0x02014b50, 0);
    cen.writeUInt16LE(20, 4); cen.writeUInt16LE(20, 6);
    cen.writeUInt16LE(0, 8); cen.writeUInt16LE(8, 10);
    cen.writeUInt32LE(0, 12);
    cen.writeUInt32LE(crc, 16);
    cen.writeUInt32LE(comp.length, 20);
    cen.writeUInt32LE(data.length, 24);
    cen.writeUInt16LE(nameBuf.length, 28);
    cen.writeUInt32LE(offset, 42);
    central.push(cen, nameBuf);
    offset += local.length + nameBuf.length + comp.length;
  }
  const centralBuf = Buffer.concat(central);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(files.length, 8);
  eocd.writeUInt16LE(files.length, 10);
  eocd.writeUInt32LE(centralBuf.length, 12);
  eocd.writeUInt32LE(offset, 16);
  return Buffer.concat([...chunks, centralBuf, eocd]);
}

try {
  if (existsSync("extension/manifest.json")) {
    const files = walk("extension").map((f) => ({ name: f.rel, data: readFileSync(f.full) }));
    writeFileSync("public/extension.zip", zip(files));
    console.log(`[build] packaged public/extension.zip (${files.length} files)`);
  }
} catch (e) {
  console.warn("[build] extension packaging skipped:", e.message);
}
